<?php

/**
 * @file
 * Test module for Imagemagick.
 */

use Drupal\imagemagick\ImagemagickExecArguments;

/**
 * Implements hook_imagemagick_pre_parse_file_alter().
 *
 * @deprecated Kept only for BC test coverage, will be removed in 8.x-3.0.
 * @see https://www.drupal.org/project/imagemagick/issues/3043136
 */
function imagemagick_test_imagemagick_pre_parse_file_alter(ImagemagickExecArguments $arguments) {
  \Drupal::service('logger.channel.image')->info('Deprecated');
}

/**
 * Implements hook_imagemagick_arguments_alter().
 *
 * @deprecated Kept only for BC test coverage, will be removed in 8.x-3.0.
 * @see https://www.drupal.org/project/imagemagick/issues/3043136
 */
function imagemagick_test_imagemagick_arguments_alter(ImagemagickExecArguments $arguments, $command) {
  \Drupal::service('logger.channel.image')->info('Deprecated');
}

/**
 * Implements hook_imagemagick_post_save_alter().
 *
 * @deprecated Kept only for BC test coverage, will be removed in 8.x-3.0.
 * @see https://www.drupal.org/project/imagemagick/issues/3043136
 */
function imagemagick_test_imagemagick_post_save_alter(ImagemagickExecArguments $arguments) {
  \Drupal::service('logger.channel.image')->info('Deprecated');
}
